# Generated by Codex on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="target_role",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
