# Generated by Django 5.2.15 on 2026-06-13 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('certificate_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('issued_for', models.CharField(help_text='Example: Python Aptitude Test, Mock Interview Completion', max_length=200)),
                ('score', models.PositiveIntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('verification_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
